version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: scheduler_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - scheduler-network

  backend:
    build: 
      context: ./Backend
    container_name: scheduling_backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - scheduler-network
    tty: true

  frontend:
    build:
      context: ./frontend
    container_name: scheduling_frontend
    ports:
      - "3000:5173"  # Access React app at http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - scheduler-network

volumes:
  mongo_data:

networks:
  scheduler-network:
    driver: bridge